### PR TITLE
Draft - split system in/out responsibilities

### PR DESCRIPTION
**Pull request by euloong**
- Created toString method in Book class to format the string output, removed string format from displayavailableBooks in MainMenu.
- Moved manageOptions from MainMenu to BibliotecaApp, updated tests.
- Changed the if-else loop to a switch.
- Moved checkOutBook to BibliotecaApp to handle System inputs.
- IntelliJ was pushing for methods to be static as main had to be static, so I had to create new instances of objects in the methods.
- In book class, updated getCheckedOut to isCheckedOut.

**Stuck on displayAvailableBooks. Had to create a new instance of the BibliotecaApp class to access the books array but it does not store the setCheckedOut value when set to true (as a fresh array is created?)**

### CODE REVIEW

**Comment by euloong** [comment]
- Moved checkOutBook and books ArrayList back into MainMenu.
- Separated user input from manageOptions and moved into MainMenu (having problems with my test as I was previously able to use hasNext with the scanner in an if statement to handle no further inputs from the test.
- Replaced System.exit(0) in manageOptions with a boolean condition
- renamed count in countCheckedOutBooks to numberOfCheckedOutBooks

**Comment by euloong** [comment]
- removed manageOptions from manageOptions to stop the recursive loop.

**Comment by euloong** [comment]
- Set instance of MainMenu as attribute of BibliotecaApp.
- removed manage options and showOptions from checkforavailablebooks and removed showNoBooksMessage in checkOutBook (not sure what to use to continue back into showOptions in BibliotecaApp).

Need to fix my tests.

**Comment by andeemarks** [comment]
Hi Eu Loong,

Something that occurred to me on looking at this last commit is that - I
think - every single function you have takes 0 arguments... this means
every method is only operating on data it owns or can get directly.  This
is not typical of most applications, where methods are often asked to
operate on data they are given.  In particular, the book list is the main
data structure the application processes, but that doesn't mean only a
single class needs to be responsible for all aspects of processing this
data structure.  I wonder whether this is stopping you from splitting the
responsibilities more evenly?

**Comment by euloong** [comment]
- realised that in checkOutBook I should just simply check if the number of books in the array are not equal to the number of checked out books.

Stuck on implementing optionsScanner.hasNext() so my tests can stop if no further element is available for the scanner.

**Comment by euloong** [comment]
- Moved the optionsScanner back into the manageOptions so can implement a break for the tests if no further input is provided by the test.

Need to move on with the other user stories and try to refactor later.

**Comment by euloong** [comment]
Thanks Andy, I appreciate it. Ting said it's ok to continue working on the assignment up to the end of next week as the feedback is the most important learning aspect of the pre-work.

I was concerned about that, it just didn't feel right that I was starting to have a mix of MainMenu and BibliotecaApp methods. I'm pushing a refactor to fix that now.

Is it best to create a new BibliotecaAppTest class to test the routing logic? 

I found the user stories were steering me to write tests in a way to test the user input, is that the correct way to do it or should the testing focus be on the output of the methods?

**Comment by andeemarks** [comment]
Have a look at https://github.com/andeemarks/scratch.  I created it to show a simple way of separating out the testing of the parent class (BibliotecaApp) and child class (MainMenu).  Hopefully the parallels are clear.

Note: what I've done here is implement a very quick-and-dirty hand-rolled mock test using an interface (`Child`) which is implemented by both a production version of the code (`ActualChild`) and a version used _only_ for testing (`TestChild`).

This approach would help you test `BibliotecaApp` is calling `MainMenu` methods correctly without having to worry about what `MainMenu` is doing.

**Comment by euloong** [comment]
Thanks Andy, this is very useful!

**Pull request merged**
